modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
issueTrackerURL="https://github.com/ShaneYu/mc-1.19-modding-tutorial/issues"
[[mods]]
modId="tutorialmod"
version="1.0.0-1.19"
displayName="Tutorial Mod"
displayURL="https://staging.shaneyu.com/blog/post/minecraft-1-19-modding-tutorial"
logoFile="tutorialmod.png"
authors="Shane Yu (ShadowLoop)"

# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

description='''
This is a mod being built up as part of my Minecraft 1.19 modding tutorial series.
'''

[[dependencies.tutorialmod]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tutorialmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
